apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: f3ifrkn16-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: f3ifrkn16-go 
  name: f3ifrkn16-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: f3ifrkn16-go 
